AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9
  Surf Checker
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 256

Parameters:
  #This should be copy pasted to all the SAM App you are making 
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - test
      - prod

Resources:
  SurfCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName: !Sub ${Environment}-surf-checker-function
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: S3Access
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
              Resource: 
                - arn:aws:s3:::surf-pics/*
                - arn:aws:s3:::surf-pics
        - Version: '2012-10-17'
          Statement:
            - Sid: SecretsAccess
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - arn:aws:secretsmanager:ap-southeast-2:373083822301:secret:prod/surf-checker/*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.10-v1